## BERTopic

https://github.com/MaartenGr/BERTopic

https://hackernoon.com/nlp-tutorial-topic-modeling-in-python-with-bertopic-372w35l9

https://maartengr.github.io/BERTopic/#variations

Paper: https://arxiv.org/pdf/2203.05794.pdf

In [ ]:
!pip install --upgrade joblib==1.1.0

Requirement already satisfied: joblib==1.1.0 in /usr/local/lib/python3.12/dist-packages (1.1.0)

In [ ]:
import pandas as pd
from google.colab import drive
drive.mount('/content/drive')
# Dataset is now stored in a Pandas Dataframe
df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/indeed_job_dataset_clean.csv')

Mounted at /content/drive

In [ ]:
!pip install bertopic
!pip install bertopic[flair]
!pip install bertopic[gensim]
!pip install bertopic[spacy]
!pip install bertopic[use]

Collecting bertopic
  Downloading bertopic-0.17.4-py3-none-any.whl.metadata (24 kB)
Requirement already satisfied: hdbscan>=0.8.29 in /usr/local/lib/python3.12/dist-packages (from bertopic) (0.8.41)
Requirement already satisfied: umap-learn>=0.5.0 in /usr/local/lib/python3.12/dist-packages (from bertopic) (0.5.9.post2)
Requirement already satisfied: numpy>=1.20.0 in /usr/local/lib/python3.12/dist-packages (from bertopic) (2.0.2)
Requirement already satisfied: pandas>=1.1.5 in /usr/local/lib/python3.12/dist-packages (from bertopic) (2.2.2)
Requirement already satisfied: plotly>=4.7.0 in /usr/local/lib/python3.12/dist-packages (from bertopic) (5.24.1)
Requirement already satisfied: scikit-learn>=1.0 in /usr/local/lib/python3.12/dist-packages (from bertopic) (1.6.1)
Requirement already satisfied: sentence-transformers>=0.4.1 in /usr/local/lib/python3.12/dist-packages (from bertopic) (5.2.0)
Requirement already satisfied: tqdm>=4.41.1 in /usr/local/lib/python3.12/dist-packages (from bertopic) (4.67.1)
Requirement already satisfied: llvmlite>0.36.0 in /usr/local/lib/python3.12/dist-packages (from bertopic) (0.43.0)
Requirement already satisfied: scipy>=1.0 in /usr/local/lib/python3.12/dist-packages (from hdbscan>=0.8.29->bertopic) (1.16.3)
Requirement already satisfied: joblib>=1.0 in /usr/local/lib/python3.12/dist-packages (from hdbscan>=0.8.29->bertopic) (1.1.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.1.5->bertopic) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.1.5->bertopic) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.1.5->bertopic) (2025.3)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.12/dist-packages (from plotly>=4.7.0->bertopic) (9.1.2)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from plotly>=4.7.0->bertopic) (25.0)
Collecting joblib>=1.0 (from hdbscan>=0.8.29->bertopic)
  Downloading joblib-1.5.3-py3-none-any.whl.metadata (5.5 kB)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=1.0->bertopic) (3.6.0)
Requirement already satisfied: transformers<6.0.0,>=4.41.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers>=0.4.1->bertopic) (4.57.3)
Requirement already satisfied: torch>=1.11.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers>=0.4.1->bertopic) (2.9.0+cpu)
Requirement already satisfied: huggingface-hub>=0.20.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers>=0.4.1->bertopic) (0.36.0)
Requirement already satisfied: typing_extensions>=4.5.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers>=0.4.1->bertopic) (4.15.0)
Requirement already satisfied: numba>=0.51.2 in /usr/local/lib/python3.12/dist-packages (from umap-learn>=0.5.0->bertopic) (0.60.0)
Requirement already satisfied: pynndescent>=0.5 in /usr/local/lib/python3.12/dist-packages (from umap-learn>=0.5.0->bertopic) (0.5.13)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers>=0.4.1->bertopic) (3.20.0)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers>=0.4.1->bertopic) (2025.3.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers>=0.4.1->bertopic) (6.0.3)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers>=0.4.1->bertopic) (2.32.4)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers>=0.4.1->bertopic) (1.2.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas>=1.1.5->bertopic) (1.17.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (3.1.6)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers>=0.4.1->bertopic) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers>=0.4.1->bertopic) (0.22.1)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers>=0.4.1->bertopic) (0.7.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (3.0.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->huggingface-hub>=0.20.0->sentence-transformers>=0.4.1->bertopic) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->huggingface-hub>=0.20.0->sentence-transformers>=0.4.1->bertopic) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->huggingface-hub>=0.20.0->sentence-transformers>=0.4.1->bertopic) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->huggingface-hub>=0.20.0->sentence-transformers>=0.4.1->bertopic) (2025.11.12)
Downloading bertopic-0.17.4-py3-none-any.whl (154 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 154.7/154.7 kB 8.4 MB/s eta 0:00:00
Downloading joblib-1.5.3-py3-none-any.whl (309 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 309.1/309.1 kB 9.1 MB/s eta 0:00:00
Installing collected packages: joblib, bertopic
  Attempting uninstall: joblib
    Found existing installation: joblib 1.1.0
    Uninstalling joblib-1.1.0:
      Successfully uninstalled joblib-1.1.0
Successfully installed bertopic-0.17.4 joblib-1.5.3
Requirement already satisfied: bertopic[flair] in /usr/local/lib/python3.12/dist-packages (0.17.4)
Requirement already satisfied: hdbscan>=0.8.29 in /usr/local/lib/python3.12/dist-packages (from bertopic[flair]) (0.8.41)
Requirement already satisfied: umap-learn>=0.5.0 in /usr/local/lib/python3.12/dist-packages (from bertopic[flair]) (0.5.9.post2)
Requirement already satisfied: numpy>=1.20.0 in /usr/local/lib/python3.12/dist-packages (from bertopic[flair]) (2.0.2)
Requirement already satisfied: pandas>=1.1.5 in /usr/local/lib/python3.12/dist-packages (from bertopic[flair]) (2.2.2)
Requirement already satisfied: plotly>=4.7.0 in /usr/local/lib/python3.12/dist-packages (from bertopic[flair]) (5.24.1)
Requirement already satisfied: scikit-learn>=1.0 in /usr/local/lib/python3.12/dist-packages (from bertopic[flair]) (1.6.1)
Requirement already satisfied: sentence-transformers>=0.4.1 in /usr/local/lib/python3.12/dist-packages (from bertopic[flair]) (5.2.0)
Requirement already satisfied: tqdm>=4.41.1 in /usr/local/lib/python3.12/dist-packages (from bertopic[flair]) (4.67.1)
Requirement already satisfied: llvmlite>0.36.0 in /usr/local/lib/python3.12/dist-packages (from bertopic[flair]) (0.43.0)
Collecting flair>=0.7 (from bertopic[flair])
  Downloading flair-0.15.1-py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: torch>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from bertopic[flair]) (2.9.0+cpu)
Requirement already satisfied: transformers>=3.5.1 in /usr/local/lib/python3.12/dist-packages (from bertopic[flair]) (4.57.3)
Collecting boto3>=1.20.27 (from flair>=0.7->bertopic[flair])
  Downloading boto3-1.42.14-py3-none-any.whl.metadata (6.8 kB)
Collecting conllu<5.0.0,>=4.0 (from flair>=0.7->bertopic[flair])
  Downloading conllu-4.5.3-py2.py3-none-any.whl.metadata (19 kB)
Collecting deprecated>=1.2.13 (from flair>=0.7->bertopic[flair])
  Downloading deprecated-1.3.1-py2.py3-none-any.whl.metadata (5.9 kB)
Collecting ftfy>=6.1.0 (from flair>=0.7->bertopic[flair])
  Downloading ftfy-6.3.1-py3-none-any.whl.metadata (7.3 kB)
Requirement already satisfied: gdown>=4.4.0 in /usr/local/lib/python3.12/dist-packages (from flair>=0.7->bertopic[flair]) (5.2.0)
Requirement already satisfied: huggingface-hub>=0.10.0 in /usr/local/lib/python3.12/dist-packages (from flair>=0.7->bertopic[flair]) (0.36.0)
Collecting langdetect>=1.0.9 (from flair>=0.7->bertopic[flair])
  Downloading langdetect-1.0.9.tar.gz (981 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 981.5/981.5 kB 32.3 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Requirement already satisfied: lxml>=4.8.0 in /usr/local/lib/python3.12/dist-packages (from flair>=0.7->bertopic[flair]) (6.0.2)
Requirement already satisfied: matplotlib>=2.2.3 in /usr/local/lib/python3.12/dist-packages (from flair>=0.7->bertopic[flair]) (3.10.0)
Requirement already satisfied: more-itertools>=8.13.0 in /usr/local/lib/python3.12/dist-packages (from flair>=0.7->bertopic[flair]) (10.8.0)
Collecting mpld3>=0.3 (from flair>=0.7->bertopic[flair])
  Downloading mpld3-0.5.12-py3-none-any.whl.metadata (5.3 kB)
Collecting pptree>=3.1 (from flair>=0.7->bertopic[flair])
  Downloading pptree-3.1.tar.gz (3.0 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from flair>=0.7->bertopic[flair]) (2.9.0.post0)
Collecting pytorch-revgrad>=0.2.0 (from flair>=0.7->bertopic[flair])
  Downloading pytorch_revgrad-0.2.0-py3-none-any.whl.metadata (1.7 kB)
Requirement already satisfied: regex>=2022.1.18 in /usr/local/lib/python3.12/dist-packages (from flair>=0.7->bertopic[flair]) (2025.11.3)
Collecting segtok>=1.5.11 (from flair>=0.7->bertopic[flair])
  Downloading segtok-1.5.11-py3-none-any.whl.metadata (9.0 kB)
Collecting sqlitedict>=2.0.0 (from flair>=0.7->bertopic[flair])
  Downloading sqlitedict-2.1.0.tar.gz (21 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: tabulate>=0.8.10 in /usr/local/lib/python3.12/dist-packages (from flair>=0.7->bertopic[flair]) (0.9.0)
Collecting transformer-smaller-training-vocab>=0.2.3 (from flair>=0.7->bertopic[flair])
  Downloading transformer_smaller_training_vocab-0.4.2-py3-none-any.whl.metadata (7.9 kB)
Collecting wikipedia-api>=0.5.7 (from flair>=0.7->bertopic[flair])
  Downloading wikipedia_api-0.8.1.tar.gz (19 kB)
  Preparing metadata (setup.py) ... done
Collecting bioc<3.0.0,>=2.0.0 (from flair>=0.7->bertopic[flair])
  Downloading bioc-2.1-py3-none-any.whl.metadata (4.6 kB)
Requirement already satisfied: scipy>=1.0 in /usr/local/lib/python3.12/dist-packages (from hdbscan>=0.8.29->bertopic[flair]) (1.16.3)
Requirement already satisfied: joblib>=1.0 in /usr/local/lib/python3.12/dist-packages (from hdbscan>=0.8.29->bertopic[flair]) (1.5.3)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.1.5->bertopic[flair]) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.1.5->bertopic[flair]) (2025.3)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.12/dist-packages (from plotly>=4.7.0->bertopic[flair]) (9.1.2)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from plotly>=4.7.0->bertopic[flair]) (25.0)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=1.0->bertopic[flair]) (3.6.0)
Requirement already satisfied: typing_extensions>=4.5.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers>=0.4.1->bertopic[flair]) (4.15.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from torch>=1.4.0->bertopic[flair]) (3.20.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch>=1.4.0->bertopic[flair]) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.4.0->bertopic[flair]) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.4.0->bertopic[flair]) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.4.0->bertopic[flair]) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in /usr/local/lib/python3.12/dist-packages (from torch>=1.4.0->bertopic[flair]) (2025.3.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from transformers>=3.5.1->bertopic[flair]) (6.0.3)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from transformers>=3.5.1->bertopic[flair]) (2.32.4)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers>=3.5.1->bertopic[flair]) (0.22.1)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers>=3.5.1->bertopic[flair]) (0.7.0)
Requirement already satisfied: numba>=0.51.2 in /usr/local/lib/python3.12/dist-packages (from umap-learn>=0.5.0->bertopic[flair]) (0.60.0)
Requirement already satisfied: pynndescent>=0.5 in /usr/local/lib/python3.12/dist-packages (from umap-learn>=0.5.0->bertopic[flair]) (0.5.13)
Collecting jsonlines>=1.2.0 (from bioc<3.0.0,>=2.0.0->flair>=0.7->bertopic[flair])
  Downloading jsonlines-4.0.0-py3-none-any.whl.metadata (1.6 kB)
Collecting intervaltree (from bioc<3.0.0,>=2.0.0->flair>=0.7->bertopic[flair])
  Downloading intervaltree-3.2.0-py2.py3-none-any.whl.metadata (13 kB)
Collecting docopt (from bioc<3.0.0,>=2.0.0->flair>=0.7->bertopic[flair])
  Downloading docopt-0.6.2.tar.gz (25 kB)
  Preparing metadata (setup.py) ... done
Collecting botocore<1.43.0,>=1.42.14 (from boto3>=1.20.27->flair>=0.7->bertopic[flair])
  Downloading botocore-1.42.14-py3-none-any.whl.metadata (5.9 kB)
Collecting jmespath<2.0.0,>=0.7.1 (from boto3>=1.20.27->flair>=0.7->bertopic[flair])
  Downloading jmespath-1.0.1-py3-none-any.whl.metadata (7.6 kB)
Collecting s3transfer<0.17.0,>=0.16.0 (from boto3>=1.20.27->flair>=0.7->bertopic[flair])
  Downloading s3transfer-0.16.0-py3-none-any.whl.metadata (1.7 kB)
Requirement already satisfied: wrapt<3,>=1.10 in /usr/local/lib/python3.12/dist-packages (from deprecated>=1.2.13->flair>=0.7->bertopic[flair]) (2.0.1)
Requirement already satisfied: wcwidth in /usr/local/lib/python3.12/dist-packages (from ftfy>=6.1.0->flair>=0.7->bertopic[flair]) (0.2.14)
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.12/dist-packages (from gdown>=4.4.0->flair>=0.7->bertopic[flair]) (4.13.5)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.10.0->flair>=0.7->bertopic[flair]) (1.2.0)
Requirement already satisfied: six in /usr/local/lib/python3.12/dist-packages (from langdetect>=1.0.9->flair>=0.7->bertopic[flair]) (1.17.0)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=2.2.3->flair>=0.7->bertopic[flair]) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=2.2.3->flair>=0.7->bertopic[flair]) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=2.2.3->flair>=0.7->bertopic[flair]) (4.61.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=2.2.3->flair>=0.7->bertopic[flair]) (1.4.9)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=2.2.3->flair>=0.7->bertopic[flair]) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=2.2.3->flair>=0.7->bertopic[flair]) (3.2.5)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=1.4.0->bertopic[flair]) (1.3.0)
Requirement already satisfied: sentencepiece!=0.1.92,>=0.1.91 in /usr/local/lib/python3.12/dist-packages (from transformers[sentencepiece]<5.0.0,>=4.25.0->flair>=0.7->bertopic[flair]) (0.2.1)
Requirement already satisfied: protobuf in /usr/local/lib/python3.12/dist-packages (from transformers[sentencepiece]<5.0.0,>=4.25.0->flair>=0.7->bertopic[flair]) (5.29.5)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=1.4.0->bertopic[flair]) (3.0.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->transformers>=3.5.1->bertopic[flair]) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->transformers>=3.5.1->bertopic[flair]) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->transformers>=3.5.1->bertopic[flair]) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->transformers>=3.5.1->bertopic[flair]) (2025.11.12)
Requirement already satisfied: attrs>=19.2.0 in /usr/local/lib/python3.12/dist-packages (from jsonlines>=1.2.0->bioc<3.0.0,>=2.0.0->flair>=0.7->bertopic[flair]) (25.4.0)
Requirement already satisfied: accelerate>=0.26.0 in /usr/local/lib/python3.12/dist-packages (from transformers[sentencepiece,torch]<5.0,>=4.1->transformer-smaller-training-vocab>=0.2.3->flair>=0.7->bertopic[flair]) (1.12.0)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4->gdown>=4.4.0->flair>=0.7->bertopic[flair]) (2.8)
Requirement already satisfied: PySocks!=1.5.7,>=1.5.6 in /usr/local/lib/python3.12/dist-packages (from requests[socks]->gdown>=4.4.0->flair>=0.7->bertopic[flair]) (1.7.1)
Requirement already satisfied: psutil in /usr/local/lib/python3.12/dist-packages (from accelerate>=0.26.0->transformers[sentencepiece,torch]<5.0,>=4.1->transformer-smaller-training-vocab>=0.2.3->flair>=0.7->bertopic[flair]) (5.9.5)
Downloading flair-0.15.1-py3-none-any.whl (1.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 63.5 MB/s eta 0:00:00
Downloading bioc-2.1-py3-none-any.whl (33 kB)
Downloading boto3-1.42.14-py3-none-any.whl (140 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 140.6/140.6 kB 10.2 MB/s eta 0:00:00
Downloading conllu-4.5.3-py2.py3-none-any.whl (16 kB)
Downloading deprecated-1.3.1-py2.py3-none-any.whl (11 kB)
Downloading ftfy-6.3.1-py3-none-any.whl (44 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 44.8/44.8 kB 3.3 MB/s eta 0:00:00
Downloading mpld3-0.5.12-py3-none-any.whl (203 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 203.1/203.1 kB 16.4 MB/s eta 0:00:00
Downloading pytorch_revgrad-0.2.0-py3-none-any.whl (4.6 kB)
Downloading segtok-1.5.11-py3-none-any.whl (24 kB)
Downloading transformer_smaller_training_vocab-0.4.2-py3-none-any.whl (14 kB)
Downloading botocore-1.42.14-py3-none-any.whl (14.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 14.6/14.6 MB 104.9 MB/s eta 0:00:00

## Modelo General

In [ ]:
df = df[df['Description'].notna()]

import numpy as np
from bertopic import BERTopic

#The default embedding model is all-MiniLM-L6-v2 when selecting language="english"
#When calculate_probabilities=True, then it is the probabilities of all topics per document.
topic_model  = BERTopic(
    language='english',
    calculate_probabilities=True,
    verbose=True)


docs = df.Description.to_list()
#topics contains a one-to-one mapping of inputs to their modeled topic (or cluster).
#probs contains a list of probabilities that an input belongs to their assigned topic.
topics, probabilities = topic_model.fit_transform(docs)

/usr/local/lib/python3.12/dist-packages/hdbscan/robust_single_linkage_.py:175: SyntaxWarning: invalid escape sequence '\{'
  $max \{ core_k(a), core_k(b), 1/\alpha d(a,b) \}$.
WARNING:torchao.kernel.intmm:Warning: Detected no triton, on systems without Triton certain kernels will not work
2025-12-20 18:42:00,911 - BERTopic - Embedding - Transforming documents to embeddings.

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md: 0.00B [00:00, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/90.9M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

Batches:   0%|          | 0/167 [00:00<?, ?it/s]

2025-12-20 18:52:07,380 - BERTopic - Embedding - Completed ✓
2025-12-20 18:52:07,381 - BERTopic - Dimensionality - Fitting the dimensionality reduction algorithm
2025-12-20 18:52:46,003 - BERTopic - Dimensionality - Completed ✓
2025-12-20 18:52:46,005 - BERTopic - Cluster - Start clustering the reduced embeddings
2025-12-20 18:52:48,345 - BERTopic - Cluster - Completed ✓
2025-12-20 18:52:48,361 - BERTopic - Representation - Fine-tuning topics using representation models.
2025-12-20 18:52:50,057 - BERTopic - Representation - Completed ✓

In [ ]:
#topic_model.get_topic_freq().head(11)

In [ ]:
#Select one topic
#t6 = topic_model.get_topic(6)

In [ ]:
#We can get information describing each topic by calling our BERTopic object's get_topic_info() method.
topic_model.get_topic_info()

,Topic,Count,Name,Representation,Representative_Docs
0,-1,2563,-1_data_business_team_work,"[data, business, team, work, skill, ability, a...",[location el segundo ca california trusted par...
1,0,279,0_analysis_data_report_sql,"[analysis, data, report, sql, reporting, busin...",[interpret data analyze result statistical tec...
2,1,203,1_data_process_business_requirement,"[data, process, business, requirement, managem...",[review requirement completeness accuracy crea...
3,2,113,2_care_clinical_patient_report,"[care, clinical, patient, report, hospital, qu...",[data analyst community reach center crc integ...
4,3,100,3_marketing_campaign_analytics_customer,"[marketing, campaign, analytics, customer, bra...",[marketing data analyst primarily responsible ...
...,...,...,...,...,...
83,82,11,82_adobe_search_freely_surrounded,"[adobe, search, freely, surrounded, immersed, ...",[challenge adobe data scientist build generati...
84,83,11,83_spotify_game_title_panda,"[spotify, game, title, panda, analyst, glu, sc...",[role overview data analyst analytical data pa...
85,84,11,84_possession_parallel_sci_clearance,"[possession, parallel, sci, clearance, oral, m...",[big data analysis programming technique techn...
86,85,10,85_fiserv_prerequisite_financial_webster,"[fiserv, prerequisite, financial, webster, fin...",[skill reside intersection analytics technolog...
87,86,10,86_ge_analytical_web_analytics,"[ge, analytical, web, analytics, member, hoffm...",[challenging position data scientist analytic ...

In [ ]:
t6 = topic_model.get_topic(6)
res = " ".join([x for x,_ in t6])
res

'analysis business quantitative marketing ability data skill insight stakeholder project'

--------------------------------------------------------
## Built-in visualization methods

In [ ]:
topic_model.visualize_topics()

In [ ]:
#Muestra las palabras mas puntuadas de los temas con mas importancia
topic_model.visualize_barchart()

In [ ]:
#visualization allows us to view the “hierarchy” of topics
topic_model.visualize_hierarchy()

In [ ]:
#Heatman: demonstrates a heatmap of the first 100 scenarios in the dataset. Based on the cosine similarity values between topic
# embeddings, the heatmap shows the similarity between the extracted topics. Figure 4 shows that most scenarios in the dataset
# seem to have moderate to high similarities. However, there are some scenarios (see light-green colors) that are quite distinct from
# the other scenarios based on the words and phrases used by the examinees in their written responses.
topic_model.visualize_heatmap()

--------------------------------------------------------
#Topic reduction
https://maartengr.github.io/BERTopic/getting_started/topicreduction/topicreduction.html#automatic-topic-reduction

https://towardsdatascience.com/interactive-topic-modeling-with-bertopic-1ea55e7d73d8

By setting the nr_topics variable, BERTopic will find the most similar pairs of topics and merge them, starting from the least frequent topic, until we reach the value of nr_topics

`model  = BERTopic(nr_topics=20`)

if you merge topics to a low nr_topics topics will be forced to merge even though they might not actually be that similar to each other.
Instead, we can reduce the number of topics iteratively as long as a pair of topics is found that exceeds a minimum similarity of 0.9.
To use this option, we simply set nr_topics to "auto" before training our mode

`model = BERTopic(nr_topics="auto")`

In [ ]:
#Fortunately, we can reduce the number of topics after having trained a BERTopic model.
#Another advantage of doing so is that you can decide the number of topics after
# knowing how many are actually created:

#topic_model.reduce_topics(docs, nr_topics=30)
#topic_model.reduce_topics(docs, nr_topics="auto")

# New Model

In [ ]:
phrases_set = set()
time_set = set()
import time

In [ ]:
# Posibles modificaciones para minimizar la variabilidad de los resultados
# entre ejecuciones utiliznado la misma semilla
#https://maartengr.github.io/BERTopic/faq.html#why-are-the-results-not-consistent-between-runs


#from tqdm import tqdm as tqdm
import numpy as np
from bertopic import BERTopic

# Importing the library for RAM usage
import psutil


start_time = time.time()

auto_model  = BERTopic(
    language='english',
    calculate_probabilities=True,
    verbose=True,
    nr_topics="auto")
docs = df.Description.to_list()
auto_topics, auto_probabilities = auto_model.fit_transform(docs)

execution_time_seconds = round((time.time() - start_time), 2)
print("--- %s seconds ---" % execution_time_seconds)
time_set.add(execution_time_seconds)


# Getting % usage of virtual_memory ( 3rd field)
print('RAM memory % used:', psutil.virtual_memory()[2])
# Getting usage of virtual_memory in GB ( 4th field)
print('RAM Used (GB):', psutil.virtual_memory()[3]/1000000000)

2025-12-20 18:53:05,917 - BERTopic - Embedding - Transforming documents to embeddings.

Batches:   0%|          | 0/167 [00:00<?, ?it/s]

2025-12-20 19:03:12,245 - BERTopic - Embedding - Completed ✓
2025-12-20 19:03:12,247 - BERTopic - Dimensionality - Fitting the dimensionality reduction algorithm
2025-12-20 19:03:23,512 - BERTopic - Dimensionality - Completed ✓
2025-12-20 19:03:23,513 - BERTopic - Cluster - Start clustering the reduced embeddings
2025-12-20 19:03:26,081 - BERTopic - Cluster - Completed ✓
2025-12-20 19:03:26,082 - BERTopic - Representation - Extracting topics using c-TF-IDF for topic reduction.
2025-12-20 19:03:27,239 - BERTopic - Representation - Completed ✓
2025-12-20 19:03:27,241 - BERTopic - Topic reduction - Reducing number of topics
2025-12-20 19:03:27,282 - BERTopic - Representation - Fine-tuning topics using representation models.
2025-12-20 19:03:28,400 - BERTopic - Representation - Completed ✓
2025-12-20 19:03:28,403 - BERTopic - Topic reduction - Reduced number of topics from 93 to 54

--- 623.08 seconds ---
RAM memory % used: 20.8
RAM Used (GB): 2.48559616

In [ ]:
import statistics
statistics.mean(time_set)

623.08

In [ ]:
pd.set_option('display.max_columns', 900)
pd.set_option('display.max_rows', 900)
auto_model.get_topic_info()

,Topic,Count,Name,Representation,Representative_Docs
0,-1,2719,-1_data_business_team_work,"[data, business, team, work, skill, analysis, ...",[description data scientist join enterprise di...
1,0,1234,0_data_business_team_analytics,"[data, business, team, analytics, analysis, wo...",[functional area responsible leading departmen...
2,1,147,1_learning_machine_algorithm_deep,"[learning, machine, algorithm, deep, science, ...",[leverage data business principle solve large ...
3,2,129,2_data_pipeline_spark_database,"[data, pipeline, spark, database, aws, system,...",[customer facing data service consulting relev...
4,3,100,3_care_clinical_patient_report,"[care, clinical, patient, report, hospital, qu...",[data analyst community reach center crc integ...
5,4,90,4_benefit_contract_engineer_hire,"[benefit, contract, engineer, hire, company, s...",[data analytics company mountain view strong d...
6,5,50,5_lighthouse_firm_diverse_processing,"[lighthouse, firm, diverse, processing, ai, ap...",[innovate collaborate shine lighthouse center ...
7,6,43,6_research_patient_science_care,"[research, patient, science, care, scientific,...",[science technology mission rence livermore la...
8,7,38,7_indiana_life_good_big,"[indiana, life, good, big, job, individual, cl...",[good people build rewarding career working in...
9,8,37,8_clinical_care_quality_statistical,"[clinical, care, quality, statistical, data, r...",[work cooperatively ihc executive team develop...
10,9,32,9_security_forcepoint_cybersecurity_cyber,"[security, forcepoint, cybersecurity, cyber, n...",[forcepoint transforming cybersecurity focusin...
11,10,30,10_bioinformatics_biology_computational_genomic,"[bioinformatics, biology, computational, genom...",[innovative bioinformatics manager genomic tec...
12,11,30,11_deliverable_analyst_ware_load,"[deliverable, analyst, ware, load, reconcile, ...",[responsible analytic data business unit handl...
13,12,29,12_capgemini_rightshore_belonging_trademark,"[capgemini, rightshore, belonging, trademark, ...",[capgemini capgemini people country capgemini ...
14,13,27,13_technology_solution_infosys_aws,"[technology, solution, infosys, aws, azure, ti...",[job summary external role title big data engi...
15,14,24,14_capgemini_status_www_eur,"[capgemini, status, www, eur, heritage, multic...",[short description capgemini global leader con...
16,15,22,15_global_rating_science_amp,"[global, rating, science, amp, experimental, l...",[team data science team newly formed applied r...
17,16,22,16_learning_machine_deep_ml,"[learning, machine, deep, ml, science, model, ...",[data scientist machine learning engineer part...
18,17,21,17_impactful_product_quantitative_build,"[impactful, product, quantitative, build, insi...",[senior finance data scientist san francisco j...
19,18,21,18_nlp_learning_machine_deep,"[nlp, learning, machine, deep, model, ml, natu...",[develop scalable tool leveraging machine lear...
20,19,20,19_monthsof_azurecloud_minimum_accenture,"[monthsof, azurecloud, minimum, accenture, arc...",[job summary join accenture digital leave digi...
21,20,19,20_degree_ba_clearance_mathematics,"[degree, ba, clearance, mathematics, engineeri...",[machine learning data mining statistic graph ...
22,21,18,21_student_school_teaching_metis,"[student, school, teaching, metis, instructor,...",[job title job description senior data scienti...
23,22,18,22_denodo_client_understanding_technology,"[denodo, client, understanding, technology, ke...",[thoughtworks global software consultancy made...
24,23,18,23_month_aws_minimum_architecting,"[month, aws, minimum, architecting, accenture,...",[job summary join accenture digital leave digi...
25,24,18,24_image_ge_imaging_algorithm,"[image, ge, imaging, algorithm, learning, deve...",[role summary revolutionize care domain highly...
26,25,17,25_minimum_accenture_digital_premise,"[minimum, accenture, digital, premise, nosql, ...",[job summary join accenture digital leave digi...
27,26,16,26_set_algorithm_determine_model,"[set, algorithm, determine, model, order, scie...",[position description data scientist responsib...
28,27,16,27_azure_data_standard_sql,"[azure, data, standard, sql, factory, service,...",[make positive difference stand crowd fit stan...
29,28,15,28_coursework_statistic_field_ability,"[coursework, statistic, field, ability, langua...",[ba b m data science machine learning statisti...
30,29,15,29_interface_hhsc_irs_core,"[interface, hhsc, irs, core, od, hedis, trend,...",[analyze management program including data col...
31,30,15,30_pricing_statistical_learning_machine,"[pricing, statistical, learning, machine, spre...",[responsible automating pricing strategy catal...
32,31,15,31_clearance_distributable_ba_including,"[clearance, distributable, ba, including, scal...",[applying advanced analytic technique includin...
33,32,15,32_allocated_warehouse_launch_design,"[allocated, warehouse, launch, design, ownersh...",[manage data warehouse plan product group prod...
34,33,15,33_modeling_quantitative_end_requiring,"[modeling, quantitative, end, requiring, php, ...",[provide technical thought leadership designin...
35,34,15,34_chain_supply_balancing_optimization,"[chain, supply, balancing, optimization, inven...",[position description manage execute entire pr...
36,35,15,35_ability_kohler_criteo_kettle,"[ability, kohler, criteo, kettle, externally, ...",[partner business developer team maximize mark...
37,36,14,36_amd_isv_machine_learning,"[amd, isv, machine, learning, ml, capital, tec...",[capital building leading information based te...
38,37,14,37_ccas_miner_similar_poly,"[ccas, miner, similar, poly, psychology, unsup...",[current t sci f poly ccas considered b yr rel...
39,38,13,38_product_metric_evaluating_experiment,"[product, metric, evaluating, experiment, key,...",[apply expertise quantitative analysis data mi...
40,39,13,39_pharmacy_client_claim_care,"[pharmacy, client, claim, care, support, repor...",[data analyst information analysis consultatio...
41,40,13,40_analytics_participates_economics_improvement,"[analytics, participates, economics, improveme...",[position description demonstrates date expert...
42,41,13,41_research_google_machine_learning,"[research, google, machine, learning, search, ...",[accepting application january team review app...
43,42,13,42_patient_clinical_medicine_trial,"[patient, clinical, medicine, trial, digital, ...",[position summary principal data scientist per...
44,43,13,43_science_manage_accumulo_including,"[science, manage, accumulo, including, languag...",[data scientist building statistical model dev...
45,44,12,44_fargo_well_cao_wholesale,"[fargo, well, cao, wholesale, risk, eone, ihub...",[well fargo satisfy customer financial succeed...
46,45,12,45_paypal_account_currency_hold,"[paypal, account, currency, hold, payment, cap...",[fueled fundamental belief access creates oppo...
47,46,12,46_cloud_google_technical_customer,"[cloud, google, technical, customer, ml, micro...",[note applying position application automatica...
48,47,11,47_adobe_search_learning_freely,"[adobe, search, learning, freely, surrounded, ...",[challenge adobe data scientist build generati...
49,48,11,48_model_statistical_graph_mixed,"[model, statistical, graph, mixed, regression,...",[support development delivery analytic statist...
50,49,11,49_possession_parallel_sci_clearance,"[possession, parallel, sci, clearance, oral, m...",[big data analysis programming technique techn...
51,50,11,50_westrock_iot_avanade_sale,"[westrock, iot, avanade, sale, solution, ai, t...",[westrock nyse wrk partner customer provide di...
52,51,11,51_database_etl_server_sql,"[database, etl, server, sql, data, tool, ssis,...",[design develops installs configures support m...
53,52,10,52_computer_amp_degree_information,"[computer, amp, degree, information, informati...",[web amp mobile application engineering data a...

In [ ]:
for i in range(0, len(auto_model.get_topic_info()) - 1):
  t = auto_model.get_topic(i)
  res = " ".join([x for x,_ in t])
  print(res)

data business team analytics analysis work skill ability process customer
learning machine algorithm deep science python computer model technique language
data pipeline spark database aws system hadoop design build cloud
care clinical patient report hospital quality ability analysis data management
benefit contract engineer hire company salary tech senior scientist market
lighthouse firm diverse processing ai approach artificial work recruitment excellence
research patient science care scientific data computational laboratory learning machine
indiana life good big job individual claim ordinance rewarding angeles
clinical care quality statistical data related management preferred study research
security forcepoint cybersecurity cyber network detection machine learning threat science
bioinformatics biology computational genomic genomics cancer gene biological sequencing scientific
deliverable analyst ware load reconcile hedis assist reporting data elevate
capgemini rightshore belonging trademark performed accommodation risk migration job hardship
technology solution infosys aws azure title city amazon big require
capgemini status www eur heritage multicultural disclaimer covered ambition count
global rating science amp experimental learning natural intelligence linguistics impact
learning machine deep ml science model neural algorithm statistic network
impactful product quantitative build insight toughest alerting tackling impact data
nlp learning machine deep model ml natural speech problem language
monthsof azurecloud minimum accenture architecting azure designing digital implementing solution
degree ba clearance mathematics engineering obtain statistic ability python including
student school teaching metis instructor science quarter feedback learning curriculum
denodo client understanding technology key deep project role thoughtworks travel
month aws minimum architecting accenture designing digital cloud implementing party
image ge imaging algorithm learning development medical heartflow deep software
minimum accenture digital premise nosql curation visa hadoop scale informatica
set algorithm determine model order scientist large responsible data date
azure data standard sql factory service microsoft locker warehouse work
coursework statistic field ability language python analytical programming skill relocate
interface hhsc irs core od hedis trend reconciliation cm lower
pricing statistical learning machine spreetail business develop algorithm statistic quantitative
clearance distributable ba including scaling elasticsearch degree language mongodb sci
allocated warehouse launch design ownership product production infra build triage
modeling quantitative end requiring php econometrics extracting manipulating scikit product
chain supply balancing optimization inventory cost functional johnson modeling project
ability kohler criteo kettle externally pentaho passion technical skill strong
amd isv machine learning ml capital technology customer distributed crowdstrike
ccas miner similar poly psychology unsupervised supervised count yr ranking
product metric evaluating experiment key behavior spreading building exploratory analysis
pharmacy client claim care support reporting gsk pbm analytic pharmaceutical
analytics participates economics improvement provisioning mathematics ethic company science field
research google machine learning search application residency resident intelligence letter
patient clinical medicine trial digital disease scientific evidence sanofi drug
science manage accumulo including language data manipulate designing clearance ability
fargo well cao wholesale risk eone ihub finance begin reporting
paypal account currency hold payment capitalize smith money john status
cloud google technical customer ml microsoft usa technology infrastructure solution
adobe search learning freely surrounded cloud machine immersed customer discover
model statistical graph mixed regression series python skill problem sa
possession parallel sci clearance oral mining concept written ba degree
westrock iot avanade sale solution ai technical business team packaging
database etl server sql data tool ssis enterprise design spoon
computer amp degree information informatica hadoop engineering java science python

In [ ]:
auto_model.visualize_topics()